#!/bin/sh
# this file autogenerated by uniset-configurator
# {GENDATE}

RETVAL=0

usage()
{
	echo "${0##*/} {config|remove|help}"
}


config()
{
	modprobe comedi
	{MOD_PROBE}
	{CARDS_CONFIG}
}

cremove()
{
	{CARDS_REMOVE}
	{MOD_REMOVE}
	rmmod comedi
}


# See how we were called.
case "$1" in

	-c|--config)
		config
		;;
	-r|--remove)
		cremove
		;;

	-h|--help|help)
		usage
		;;
	*)
		RETVAL=1
esac

exit $RETVAL
